/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package es.gva.sanchezgarcia.jg.ut2.e5_menus.gui;

/**
 *
 * @author josegaspar
 */
public class MainWin extends javax.swing.JFrame {

    /**
     * Creates new form MainWin
     */
    public MainWin() {
        initComponents();
        // Agrupamos RadioButtons
        this.buttonGroupCasa.add(jRadioButtonMenuItemBanyo);
        this.buttonGroupCasa.add(jRadioButtonMenuItemCocina);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupCasa = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPaneLog = new javax.swing.JTextPane();
        jMenuBarCasa = new javax.swing.JMenuBar();
        jMenuCasa = new javax.swing.JMenu();
        jMenuHabitacion = new javax.swing.JMenu();
        jMenuItemHabitación1 = new javax.swing.JMenuItem();
        jMenuItemHabitacion2 = new javax.swing.JMenuItem();
        jCheckBoxMenuItemSalon = new javax.swing.JCheckBoxMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jRadioButtonMenuItemCocina = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItemBanyo = new javax.swing.JRadioButtonMenuItem();
        jMenuExtras = new javax.swing.JMenu();
        jMenuItemGaraje = new javax.swing.JMenuItem();
        jMenuItemTrastero = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Casa");
        setMinimumSize(new java.awt.Dimension(400, 300));
        setPreferredSize(new java.awt.Dimension(600, 600));
        setSize(new java.awt.Dimension(600, 600));

        jScrollPane1.setViewportView(jTextPaneLog);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jMenuCasa.setText("Casa");
        jMenuCasa.setName("casa"); // NOI18N

        jMenuHabitacion.setText("Habitación");

        jMenuItemHabitación1.setText("Habitación 1");
        jMenuHabitacion.add(jMenuItemHabitación1);

        jMenuItemHabitacion2.setText("Habitación 2");
        jMenuItemHabitacion2.setEnabled(false);
        jMenuHabitacion.add(jMenuItemHabitacion2);

        jMenuCasa.add(jMenuHabitacion);

        jCheckBoxMenuItemSalon.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jCheckBoxMenuItemSalon.setSelected(true);
        jCheckBoxMenuItemSalon.setText("Salón");
        jMenuCasa.add(jCheckBoxMenuItemSalon);
        jMenuCasa.add(jSeparator1);

        jRadioButtonMenuItemCocina.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jRadioButtonMenuItemCocina.setSelected(true);
        jRadioButtonMenuItemCocina.setText("Cocina");
        jMenuCasa.add(jRadioButtonMenuItemCocina);

        jRadioButtonMenuItemBanyo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jRadioButtonMenuItemBanyo.setText("Baño");
        jMenuCasa.add(jRadioButtonMenuItemBanyo);

        jMenuBarCasa.add(jMenuCasa);

        jMenuExtras.setText("Extras");

        jMenuItemGaraje.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItemGaraje.setText("Garaje");
        jMenuExtras.add(jMenuItemGaraje);

        jMenuItemTrastero.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItemTrastero.setText("Trastero");
        jMenuExtras.add(jMenuItemTrastero);

        jMenuBarCasa.add(jMenuExtras);

        setJMenuBar(jMenuBarCasa);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupCasa;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemSalon;
    private javax.swing.JMenuBar jMenuBarCasa;
    private javax.swing.JMenu jMenuCasa;
    private javax.swing.JMenu jMenuExtras;
    private javax.swing.JMenu jMenuHabitacion;
    private javax.swing.JMenuItem jMenuItemGaraje;
    private javax.swing.JMenuItem jMenuItemHabitacion2;
    private javax.swing.JMenuItem jMenuItemHabitación1;
    private javax.swing.JMenuItem jMenuItemTrastero;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItemBanyo;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItemCocina;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTextPane jTextPaneLog;
    // End of variables declaration//GEN-END:variables
}
