/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package es.gva.sanchezgarcia.jg.ut2.e5_menus.gui;

/**
 *
 * @author josegaspar
 */
public class MainWin extends javax.swing.JFrame {
    private int contadorHabitacion;
    private int contadorSalon;
    private int contadorCocina;
    private int contadorBanyo;
    private int contadorGaraje;
    private int contadorTrastero;
    
    /**
     * Creates new form MainWin
     */
    public MainWin() {
        initComponents();
        // Agrupamos RadioButtons
        this.buttonGroupCasa.add(jRadioButtonMenuItemBanyo);
        this.buttonGroupCasa.add(jRadioButtonMenuItemCocina);
        this.contadorHabitacion=0;
        this.contadorSalon=0;
        this.contadorCocina=0;
        this.contadorBanyo=0;
        this.contadorGaraje=0;
        this.contadorTrastero=0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupCasa = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPaneLog = new javax.swing.JTextPane();
        jMenuBarCasa = new javax.swing.JMenuBar();
        jMenuCasa = new javax.swing.JMenu();
        jMenuHabitacion = new javax.swing.JMenu();
        jMenuItemHabitación1 = new javax.swing.JMenuItem();
        jMenuItemHabitacion2 = new javax.swing.JMenuItem();
        jCheckBoxMenuItemSalon = new javax.swing.JCheckBoxMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jRadioButtonMenuItemCocina = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItemBanyo = new javax.swing.JRadioButtonMenuItem();
        jMenuExtras = new javax.swing.JMenu();
        jMenuItemGaraje = new javax.swing.JMenuItem();
        jMenuItemTrastero = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Casa");
        setMinimumSize(new java.awt.Dimension(400, 300));
        setPreferredSize(new java.awt.Dimension(600, 600));
        setSize(new java.awt.Dimension(600, 600));

        jScrollPane1.setViewportView(jTextPaneLog);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jMenuCasa.setText("Casa");
        jMenuCasa.setName("casa"); // NOI18N

        jMenuHabitacion.setText("Habitación");

        jMenuItemHabitación1.setText("Habitación 1");
        jMenuItemHabitación1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemHabitación1ActionPerformed(evt);
            }
        });
        jMenuHabitacion.add(jMenuItemHabitación1);

        jMenuItemHabitacion2.setText("Habitación 2");
        jMenuItemHabitacion2.setEnabled(false);
        jMenuHabitacion.add(jMenuItemHabitacion2);

        jMenuCasa.add(jMenuHabitacion);

        jCheckBoxMenuItemSalon.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jCheckBoxMenuItemSalon.setSelected(true);
        jCheckBoxMenuItemSalon.setText("Salón");
        jCheckBoxMenuItemSalon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItemSalonActionPerformed(evt);
            }
        });
        jMenuCasa.add(jCheckBoxMenuItemSalon);
        jMenuCasa.add(jSeparator1);

        jRadioButtonMenuItemCocina.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jRadioButtonMenuItemCocina.setSelected(true);
        jRadioButtonMenuItemCocina.setText("Cocina");
        jRadioButtonMenuItemCocina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItemCocinaActionPerformed(evt);
            }
        });
        jMenuCasa.add(jRadioButtonMenuItemCocina);

        jRadioButtonMenuItemBanyo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jRadioButtonMenuItemBanyo.setText("Baño");
        jRadioButtonMenuItemBanyo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItemBanyoActionPerformed(evt);
            }
        });
        jMenuCasa.add(jRadioButtonMenuItemBanyo);

        jMenuBarCasa.add(jMenuCasa);

        jMenuExtras.setText("Extras");

        jMenuItemGaraje.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItemGaraje.setText("Garaje");
        jMenuItemGaraje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGarajeActionPerformed(evt);
            }
        });
        jMenuExtras.add(jMenuItemGaraje);

        jMenuItemTrastero.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItemTrastero.setText("Trastero");
        jMenuItemTrastero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTrasteroActionPerformed(evt);
            }
        });
        jMenuExtras.add(jMenuItemTrastero);

        jMenuBarCasa.add(jMenuExtras);

        setJMenuBar(jMenuBarCasa);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemHabitación1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemHabitación1ActionPerformed
        // TODO add your handling code here:
        contadorHabitacion++;
        String cad;
        if(contadorHabitacion==1)
            cad="Has entrado a la habitación "+contadorHabitacion+" vez.";
        else
            cad="Has entrado a la habitación "+contadorHabitacion+" veces.";
            
        System.out.println(cad);
        String txt=jTextPaneLog.getText();
        txt=txt+cad+"\n";
        jTextPaneLog.setText(txt);
        
    }//GEN-LAST:event_jMenuItemHabitación1ActionPerformed

    private void jCheckBoxMenuItemSalonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItemSalonActionPerformed
        // TODO add your handling code here:
        String estado="";
        
        contadorSalon++;
        String cad;
        if(contadorSalon==1)
            cad="Has entrado al salón "+contadorSalon+" vez. Estado ";
        else
            cad="Has entrado al salón "+contadorSalon+" veces. Estado ";
        
        if(jCheckBoxMenuItemSalon.getState())
            estado="activado.";
        else
            estado="desactivado.";
        
        cad=cad+estado;    
        System.out.println(cad);
        String txt=jTextPaneLog.getText();
        txt=txt+cad+"\n";
        jTextPaneLog.setText(txt);
        
        
    }//GEN-LAST:event_jCheckBoxMenuItemSalonActionPerformed

    private void jRadioButtonMenuItemCocinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItemCocinaActionPerformed
        // TODO add your handling code here:
        String estado="";
        
        contadorCocina++;
        String cad;
        if(contadorCocina==1)
            cad="Has entrado en la cocina "+contadorCocina+" vez. Estado ";
        else
            cad="Has entrado en la cocina "+contadorCocina+" veces. Estado ";
        
        if(jRadioButtonMenuItemCocina.isSelected())
            estado="activado.";
        else
            estado="desactivado.";
        
        cad=cad+estado;    
        System.out.println(cad);
        String txt=jTextPaneLog.getText();
        txt=txt+cad+"\n";
        jTextPaneLog.setText(txt);
    }//GEN-LAST:event_jRadioButtonMenuItemCocinaActionPerformed

    private void jRadioButtonMenuItemBanyoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItemBanyoActionPerformed
        // TODO add your handling code here:
        String estado="";
        
        contadorBanyo++;
        String cad;
        if(contadorBanyo==1)
            cad="Has entrado al baño "+contadorBanyo+" vez. Estado ";
        else
            cad="Has entrado al baño "+contadorBanyo+" veces. Estado ";
        
        if(jRadioButtonMenuItemBanyo.isSelected())
            estado="activado.";
        else
            estado="desactivado.";
        
        cad=cad+estado;    
        System.out.println(cad);
        String txt=jTextPaneLog.getText();
        txt=txt+cad+"\n";
        jTextPaneLog.setText(txt);
    }//GEN-LAST:event_jRadioButtonMenuItemBanyoActionPerformed

    private void jMenuItemGarajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGarajeActionPerformed
        // TODO add your handling code here:
        
        contadorGaraje++;
        String cad;
        if(contadorGaraje==1)
            cad="Has entrado en el garaje "+contadorGaraje+" vez.";
        else
            cad="Has entrado en el garaje "+contadorGaraje+" veces.";
       
        System.out.println(cad);
        String txt=jTextPaneLog.getText();
        txt=txt+cad+"\n";
        jTextPaneLog.setText(txt);
    }//GEN-LAST:event_jMenuItemGarajeActionPerformed

    private void jMenuItemTrasteroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTrasteroActionPerformed
        // TODO add your handling code here:
       
        contadorTrastero++;
        String cad;
        if(contadorTrastero==1)
            cad="Has entrado en el trastero "+contadorTrastero+" vez.";
        else
            cad="Has entrado en el trastero "+contadorTrastero+" veces.";
       
        System.out.println(cad);
        String txt=jTextPaneLog.getText();
        txt=txt+cad+"\n";
        jTextPaneLog.setText(txt);
    }//GEN-LAST:event_jMenuItemTrasteroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupCasa;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemSalon;
    private javax.swing.JMenuBar jMenuBarCasa;
    private javax.swing.JMenu jMenuCasa;
    private javax.swing.JMenu jMenuExtras;
    private javax.swing.JMenu jMenuHabitacion;
    private javax.swing.JMenuItem jMenuItemGaraje;
    private javax.swing.JMenuItem jMenuItemHabitacion2;
    private javax.swing.JMenuItem jMenuItemHabitación1;
    private javax.swing.JMenuItem jMenuItemTrastero;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItemBanyo;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItemCocina;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTextPane jTextPaneLog;
    // End of variables declaration//GEN-END:variables
}
