/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package es.gva.sanchezgarcia.jg.ut2.e3_panels.gui;

import es.gva.sanchezgarcia.jg.ut2.e3_panels.logic.LogicApp;
import java.awt.Component;
import javax.swing.AbstractListModel;
import javax.swing.JPanel;
import javax.swing.ListModel;

/**
 *
 * @author josegaspar
 */
public class CoolJFrame extends javax.swing.JFrame {
    private LogicApp app;
    /**
     * Modelo abstracto para cargar el listado de actores en el JList
     * @param actores
     * @return 
     */
    private AbstractListModel<String> getModeloListadoActores(String[] actores)
    {
        return (new AbstractListModel<String>() {
            @Override
            public int getSize() {
                //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
                return actores.length;
            }

            @Override
            public String getElementAt(int i) {
                //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
                return actores[i];
            }
        });
    }
    
    
    /**
     * Creates new form CoolJFrame
     */
    public CoolJFrame() {
        initComponents();
        // Cargamos datos de la aplicación
        this.app=new LogicApp();
        
        // Carpamos datos en la pestña Sinopsis;
        jTextPaneSinopsis.setText(app.getPelicula().getSinopsis());
        
        // Cargamos reparto
        String actores[]=app.getListadoActores();
        AbstractListModel<String> model=this.getModeloListadoActores(actores);
        this.jListActores.setModel(model);
        
        // Seleccionamos el primer actor
        this.jListActores.setSelectedIndex(0);
        this.jTextPaneRepartoInfo.setText(app.getPelicula().getReparto().get(0).getBiografia());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSuperior = new javax.swing.JPanel();
        jToolBarSuperior = new javax.swing.JToolBar();
        jButtonBuscar = new javax.swing.JButton();
        jTextFieldBuscar = new javax.swing.JTextField();
        jPanelCentral = new javax.swing.JPanel();
        jTabbedPaneCentral = new javax.swing.JTabbedPane();
        jPanelSinopsis = new javax.swing.JPanel();
        jScrollPaneSinopsis = new javax.swing.JScrollPane();
        jTextPaneSinopsis = new javax.swing.JTextPane();
        jPanelReparto = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListActores = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPaneRepartoInfo = new javax.swing.JTextPane();
        jPanelInferior = new javax.swing.JPanel();
        jLabelInfo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cine JPanel");
        setMinimumSize(new java.awt.Dimension(300, 300));
        setName("Cool JFrame"); // NOI18N

        jPanelSuperior.setBackground(new java.awt.Color(255, 0, 51));
        jPanelSuperior.setMinimumSize(new java.awt.Dimension(300, 60));
        jPanelSuperior.setPreferredSize(new java.awt.Dimension(600, 50));

        jToolBarSuperior.setRollover(true);
        jToolBarSuperior.setMaximumSize(new java.awt.Dimension(600, 50));
        jToolBarSuperior.setMinimumSize(new java.awt.Dimension(300, 50));
        jToolBarSuperior.setPreferredSize(new java.awt.Dimension(575, 50));

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.setFocusable(false);
        jButtonBuscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonBuscar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBarSuperior.add(jButtonBuscar);

        jTextFieldBuscar.setText("Escriba aquí el actor que desa buscar.");
        jTextFieldBuscar.setMinimumSize(new java.awt.Dimension(300, 40));
        jTextFieldBuscar.setPreferredSize(new java.awt.Dimension(550, 40));
        jToolBarSuperior.add(jTextFieldBuscar);

        javax.swing.GroupLayout jPanelSuperiorLayout = new javax.swing.GroupLayout(jPanelSuperior);
        jPanelSuperior.setLayout(jPanelSuperiorLayout);
        jPanelSuperiorLayout.setHorizontalGroup(
            jPanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 666, Short.MAX_VALUE)
            .addGroup(jPanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelSuperiorLayout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(jToolBarSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE)
                    .addGap(15, 15, 15)))
        );
        jPanelSuperiorLayout.setVerticalGroup(
            jPanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(jPanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelSuperiorLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jToolBarSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 10, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanelSuperior, java.awt.BorderLayout.NORTH);

        jPanelCentral.setBackground(new java.awt.Color(255, 255, 51));

        jTabbedPaneCentral.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPaneCentralStateChanged(evt);
            }
        });

        jScrollPaneSinopsis.setMinimumSize(new java.awt.Dimension(300, 300));
        jScrollPaneSinopsis.setPreferredSize(new java.awt.Dimension(600, 600));
        jScrollPaneSinopsis.setViewportView(jTextPaneSinopsis);

        javax.swing.GroupLayout jPanelSinopsisLayout = new javax.swing.GroupLayout(jPanelSinopsis);
        jPanelSinopsis.setLayout(jPanelSinopsisLayout);
        jPanelSinopsisLayout.setHorizontalGroup(
            jPanelSinopsisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 646, Short.MAX_VALUE)
            .addGroup(jPanelSinopsisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSinopsisLayout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(jScrollPaneSinopsis, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanelSinopsisLayout.setVerticalGroup(
            jPanelSinopsisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 406, Short.MAX_VALUE)
            .addGroup(jPanelSinopsisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelSinopsisLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPaneSinopsis, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jTabbedPaneCentral.addTab("Sinopsis", jPanelSinopsis);

        jListActores.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Actori 1", "Actor 2", "Actor 3" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListActores.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListActoresValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jListActores);

        jScrollPane2.setViewportView(jTextPaneRepartoInfo);

        javax.swing.GroupLayout jPanelRepartoLayout = new javax.swing.GroupLayout(jPanelReparto);
        jPanelReparto.setLayout(jPanelRepartoLayout);
        jPanelRepartoLayout.setHorizontalGroup(
            jPanelRepartoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRepartoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(530, 530, 530))
            .addGroup(jPanelRepartoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelRepartoLayout.createSequentialGroup()
                    .addGap(129, 129, 129)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
                    .addGap(10, 10, 10)))
        );
        jPanelRepartoLayout.setVerticalGroup(
            jPanelRepartoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRepartoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanelRepartoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelRepartoLayout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                    .addGap(10, 10, 10)))
        );

        jTabbedPaneCentral.addTab("Reparto", jPanelReparto);

        javax.swing.GroupLayout jPanelCentralLayout = new javax.swing.GroupLayout(jPanelCentral);
        jPanelCentral.setLayout(jPanelCentralLayout);
        jPanelCentralLayout.setHorizontalGroup(
            jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 666, Short.MAX_VALUE)
            .addGroup(jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelCentralLayout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(jTabbedPaneCentral)
                    .addGap(10, 10, 10)))
        );
        jPanelCentralLayout.setVerticalGroup(
            jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 453, Short.MAX_VALUE)
            .addGroup(jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelCentralLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jTabbedPaneCentral)
                    .addGap(10, 10, 10)))
        );

        jTabbedPaneCentral.getAccessibleContext().setAccessibleName("Sinopsis");

        getContentPane().add(jPanelCentral, java.awt.BorderLayout.CENTER);

        jPanelInferior.setBackground(new java.awt.Color(204, 255, 255));
        jPanelInferior.setMinimumSize(new java.awt.Dimension(300, 50));
        jPanelInferior.setPreferredSize(new java.awt.Dimension(600, 60));

        jLabelInfo.setText("Etiqueta informativa");
        jLabelInfo.setMaximumSize(new java.awt.Dimension(600, 60));
        jLabelInfo.setMinimumSize(new java.awt.Dimension(300, 60));

        javax.swing.GroupLayout jPanelInferiorLayout = new javax.swing.GroupLayout(jPanelInferior);
        jPanelInferior.setLayout(jPanelInferiorLayout);
        jPanelInferiorLayout.setHorizontalGroup(
            jPanelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 666, Short.MAX_VALUE)
            .addGroup(jPanelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelInferiorLayout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(jLabelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)))
        );
        jPanelInferiorLayout.setVerticalGroup(
            jPanelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(jPanelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelInferiorLayout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(jLabelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)))
        );

        getContentPane().add(jPanelInferior, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPaneCentralStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPaneCentralStateChanged
        // TODO add your handling code here:
        String informacion="";
        
        int indiceTab=jTabbedPaneCentral.getSelectedIndex();
        System.out.println("IndiceTab: "+indiceTab);
        switch(indiceTab){
            case 0:{informacion="la sinopsis";break;}
            case 1:{informacion="el reparto";break;}
        }
        
        this.jLabelInfo.setText("Se está mostrando información sobre "+informacion+" de la pelicula.");
        
        
    }//GEN-LAST:event_jTabbedPaneCentralStateChanged
/**
 * Capturamos el evento que se produce cuando se cambia el valor seleccionado en la lista.
 * @param evt 
 */
    private void jListActoresValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListActoresValueChanged
        // TODO add your handling code here:
        int indiceSeleccion=jListActores.getSelectedIndex();
        
        this.jTextPaneRepartoInfo.setText(app.getPelicula().getReparto().get(indiceSeleccion).getBiografia());
    }//GEN-LAST:event_jListActoresValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CoolJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CoolJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CoolJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CoolJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CoolJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JLabel jLabelInfo;
    private javax.swing.JList<String> jListActores;
    private javax.swing.JPanel jPanelCentral;
    private javax.swing.JPanel jPanelInferior;
    private javax.swing.JPanel jPanelReparto;
    private javax.swing.JPanel jPanelSinopsis;
    private javax.swing.JPanel jPanelSuperior;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPaneSinopsis;
    private javax.swing.JTabbedPane jTabbedPaneCentral;
    private javax.swing.JTextField jTextFieldBuscar;
    private javax.swing.JTextPane jTextPaneRepartoInfo;
    private javax.swing.JTextPane jTextPaneSinopsis;
    private javax.swing.JToolBar jToolBarSuperior;
    // End of variables declaration//GEN-END:variables
}
